# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e491639d4aac4af9be1df4b408fb9ac"
name = "referral-company"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,read_customers,write_customers,read_discounts,write_discounts,read_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/daisychain"
subpath = "daisychain"
prefix = "apps"
