api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "daisychain-discount-function"
type = "function"
uid = "3ba5dc2b-bbac-6b82-1284-cda11b63414f1ea49319"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart_delivery_options_discounts_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/daisychain-discount-function.wasm"
  watch = [ "src/**/*.rs" ]
